Drkey feature pr6
juagargi/scion pull request #19
Opened 2020-10-02 11:04 UTC by JordiSubira

This PR includes basic functionalities for the DRKey feautre in the CS, among them:

- ServiceStore which encompasses the logic and persistance for DRKey within the CS.
- DRKeyFetcher using the gRPC stack introduced in https://github.com/scionproto/scion/pull/3862
- DRKeyService which also uses the new gRPC stack and handles request to the CS.

2020-10-06 13:33 UTC, juagargi requested changes
Good progress!
There are some things I would change (some or all of which might have been inherited to you by the previous existing DRKey code); please look at my comments.

> Reviewed 82 of 83 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/19#-:-MItFBZe7XF_ETWJMxmF:b-rardsa)* status: 82 of 83 files reviewed, 11 unresolved discussions (waiting on @JordiSubira and @juagargi)

___
*[go/cs/config/drkey.go, line 69 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItE_Rl6rE159BubcRX:-MItE_Rl6rE159BubcRY:b-f7w5ds) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/cs/config/drkey.go#L69)):*
> ```Go
> 	cfg.enabled = true
> 	if cfg.EpochDuration.Duration == 0 {
> 		cfg.enabled = false
> ```

Let's allow config not to have a `Duration`:
either we don't provide a `DefaultEpochDuration`, or we allow it not to show up.
___
*[go/lib/drkey/exchange/grpc.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItU36q6dwAANt9cvOk:-MItU36q6dwAANt9cvOl:bb7phvt) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/lib/drkey/exchange/grpc.go#L29)):*
> ```Go
> 	tlsInfo, ok := peer.AuthInfo.(credentials.TLSInfo)
> 	if !ok {
> 		return serrors.New("not TLS credentials provided",
> ```

typo
___
*[go/pkg/cs/drkey/prefetcher.go, line 31 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy5fJXB-xmigFrwAAq:-MIy5fJXB-xmigFrwAAr:bhoxclq) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/prefetcher.go#L31)):*
> ```Go
> 
> // Prefetcher is in charge of getting the level 1 keys before they expire.
> type Prefetcher struct {
> ```

We'll need to test the `Prefetcher` gets the keys before they expire, and it retries if there is an error.
___
*[go/pkg/cs/drkey/secret_value_store.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy3c2kDfUtZ7HvLFZZ:-MIy3c2kDfUtZ7HvLFZ_:b-4bs3lm) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/secret_value_store.go#L29)):*
> ```Go
> // SecretValueStore keeps the current and next secret values and removes the expired ones.
> type SecretValueStore struct {
> 	cache map[int64]drkey.SV
> ```

Maybe not for now, but I would refactor this whole class into something simpler and more consistent with the intentions: e.g. using two members `actual` and `next` to represent this and next secret values, or a ring buffer for them, etc.
Maybe for now add a `TODO` so it's clear that we will rework this.
___
*[go/pkg/cs/drkey/service_store.go, line 44 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIu0K2W-3pjKkU636y_:-MIu0K2W-3pjKkU636ya:b-5kqn1q) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/service_store.go#L44)):*
> ```Go
> 	Fetcher      Fetcher
> }
> ```

it would be great if you added a line
```go
var _ drkeystorage.ServiceStore = (*ServiceStore)(nil)
```
___
*[go/pkg/cs/drkey/store_test.go, line 132 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy4eVu7DBTQ-89ykVo:-MIy4eVu7DBTQ-89ykVp:b-4p83vt) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/store_test.go#L132)):*
> ```Go
> }
> 
> func TestDeriveLvl1Key(t *testing.T) {
> ```

Move the `ServiceStore` test to its own file. That way, when we change the `SecretValueStore` we should see affected tests only about the secret value store and factory.
___
*[go/pkg/cs/drkey/testcommons.go, line 15 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItSTHlB38gnWFeFebS:-MItSTHlB38gnWFeFebT:b8mmue2) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/testcommons.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package drkey
> ```

move it to its own package
___
*[go/pkg/cs/drkey/grpc/drkey_fetcher.go, line 41 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIxl8l98URPtL4hYCvJ:-MIxl8l98URPtL4hYCvK:bkkm7w0) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/drkey_fetcher.go#L41)):*
> ```Go
> 	Router trust.Router
> }
> ```

it would be good to have an explicit line like:
```go
var _ csdrkey.Fetcher = (*DRKeyFetcher)(nil)
```
___
*[go/pkg/cs/drkey/grpc/drkey_service.go, line 120 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItwqy72GAB8ufkUuw7:-MItwqy821clSgwlV4oF:bhsx3r5) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/drkey_service.go#L120)):*
> ```
> drkey.SrcIA.Write(rawKey)
> 	drkey.DstIA.Write(rawKey[addr.IABytes:])
> ```
I think it would be better to have fields for `SrcIA` and `DstIA` as part of the `DRKeyLvl1Response`, and not pack them into the raw key buffer.
___
*[go/pkg/cs/drkey/grpc/drkey_service.go, line 135 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItxJeRBqHQZxuhSUcK:-MItxJeRBqHQZxuhSUcL:bweimnd) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/drkey_service.go#L135)):*
> ```Go
> func (d *DRKeyServer) DRKeyLvl2(ctx context.Context,
> 	req *dkpb.DRKeyLvl2Request) (*dkpb.DRKeyLvl2Response, error) {
> 	peer, _ := peer.FromContext(ctx)
> ```

don't forget to check the error, like you did in the `DRKeyLvl1` function.
___
*[go/pkg/cs/drkey/grpc/lvl1_exchange_test.go, line 101 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItDTDj-ZyeYXhNMT5i:-MItDTDj-ZyeYXhNMT5j:b-4x7q9d) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/lvl1_exchange_test.go#L101)):*
> ```Go
> 		GetClientCertificate:  mgr.GetClientCertificate,
> 		VerifyPeerCertificate: mgr.VerifyPeerCertificate,
> 		VerifyConnection: func(cs tls.ConnectionState) error {
> ```

this is what you mentioned building only with go 1.15, isn't it?


<!-- Sent from Reviewable.io -->

2020-10-14 13:16 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/19)* status: 68 of 92 files reviewed, 11 unresolved discussions (waiting on @juagargi)

___
*[go/cs/config/drkey.go, line 69 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItE_Rl6rE159BubcRX:-MJbBWkz7pLAMaWLBUOX:bhnmp90) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/cs/config/drkey.go#L69)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Let's allow config not to have a `Duration`:
either we don't provide a `DefaultEpochDuration`, or we allow it not to show up.
</blockquote></details>

I just assigned the default duration in case none is given in the config file.
___
*[go/lib/drkey/exchange/grpc.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItU36q6dwAANt9cvOk:-MJbCG23-xlp6oR4o4jI:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/lib/drkey/exchange/grpc.go#L29)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/prefetcher.go, line 31 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy5fJXB-xmigFrwAAq:-MJbCSSd9U-ImxtxYUAY:bnp5ff0) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/prefetcher.go#L31)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

We'll need to test the `Prefetcher` gets the keys before they expire, and it retries if there is an error.
</blockquote></details>

I created a test for the GetLvl1Key in the store_service, since this function contains the logic of the fetching procedure. The prefetcher run task itself is pretty simple and I don't know if we really need to the that, in case we would want to, we should use an inner-class function timeFcn (similar to secret_value_store) so that we can mock the time.Now() function in the tests.
___
*[go/pkg/cs/drkey/secret_value_store.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy3c2kDfUtZ7HvLFZZ:-MJbDIcx8IcVdbDbY8Up:b-jzu5y4) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/secret_value_store.go#L29)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Maybe not for now, but I would refactor this whole class into something simpler and more consistent with the intentions: e.g. using two members `actual` and `next` to represent this and next secret values, or a ring buffer for them, etc.
Maybe for now add a `TODO` so it's clear that we will rework this.
</blockquote></details>

At the momento, I added the comment and in a near future we can discuss that further.
___
*[go/pkg/cs/drkey/service_store.go, line 44 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIu0K2W-3pjKkU636y_:-MJbDXEnESKZFROYlJUf:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/service_store.go#L44)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

it would be great if you added a line
```go
var _ drkeystorage.ServiceStore = (*ServiceStore)(nil)
```
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/grpc/drkey_fetcher.go, line 41 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIxl8l98URPtL4hYCvJ:-MJbDczE06fP9ROi_UqI:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/drkey_fetcher.go#L41)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

it would be good to have an explicit line like:
```go
var _ csdrkey.Fetcher = (*DRKeyFetcher)(nil)
```
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/grpc/drkey_service.go, line 120 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItwqy72GAB8ufkUuw7:-MJbDePo4BUsWOLseJyI:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/drkey_service.go#L120)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

> ```
> drkey.SrcIA.Write(rawKey)
> 	drkey.DstIA.Write(rawKey[addr.IABytes:])
> ```
I think it would be better to have fields for `SrcIA` and `DstIA` as part of the `DRKeyLvl1Response`, and not pack them into the raw key buffer.
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/grpc/drkey_service.go, line 135 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItxJeRBqHQZxuhSUcK:-MJbDhcbCR2odCwcQkDg:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/drkey_service.go#L135)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

don't forget to check the error, like you did in the `DRKeyLvl1` function.
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/grpc/lvl1_exchange_test.go, line 101 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItDTDj-ZyeYXhNMT5i:-MJbDlP30-zdJ8gCAnhj:b-i0xe0e) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/grpc/lvl1_exchange_test.go#L101)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

this is what you mentioned building only with go 1.15, isn't it?
</blockquote></details>

As accorded, I have implemented the alternative I think it might work with Go1.13 , although is not as neat as the one using VerfiyConnection. This alternative implements the TransportCredentials interface by extending the TLS credentials provided by the grpc/credentials package. This is further developed in go/pkg/trsut/transport_credentials.go
___
*[go/pkg/cs/drkey/store_test.go, line 132 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy4eVu7DBTQ-89ykVo:-MJbDVb-2Amjzij-_W2J:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/store_test.go#L132)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Move the `ServiceStore` test to its own file. That way, when we change the `SecretValueStore` we should see affected tests only about the secret value store and factory.
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/testcommons.go, line 15 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MItSTHlB38gnWFeFebS:-MJbCP0lDWqWBGFW05qi:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/testcommons.go#L15)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

move it to its own package
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-15 15:11 UTC, juagargi requested changes
Nice!
Very few changes proposed. We'll also have to remove commented out code in this PR before merging.

> Reviewed 22 of 24 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/19#-:-MJgnitcDqrXh0Q1L-tN:bvrgxux)* status: all files reviewed, 3 unresolved discussions (waiting on @JordiSubira)

___
*[go/pkg/cs/drkey/prefetcher.go, line 31 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy5fJXB-xmigFrwAAq:-MJgWF3E2Z6rBHOxYfCv:bd9pzky) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/prefetcher.go#L31)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I created a test for the GetLvl1Key in the store_service, since this function contains the logic of the fetching procedure. The prefetcher run task itself is pretty simple and I don't know if we really need to the that, in case we would want to, we should use an inner-class function timeFcn (similar to secret_value_store) so that we can mock the time.Now() function in the tests.
</blockquote></details>

For now add a note in the "to improve" list, that mentions the fetcher should be improved so that it retries even if the underlaying call fails. Also mention we can improve the trigger / timer in it.
___
*[go/pkg/cs/drkey/service_store_test.go, line 107 at r2](https://reviewable.io/reviews/juagargi/scion/19#-MJgJk2Z63Lz0U2GddyN:-MJgJk2_CuMX1xdkfbYb:b-2yvde1) ([raw file](https://github.com/juagargi/scion/blob/18468be11f0cf573cbee0cac25751e49a04fefe1/go/pkg/cs/drkey/service_store_test.go#L107)):*
> ```Go
> 
> func newLvl1Database(t *testing.T) (*drkeydbsqlite.Lvl1Backend, func()) {
> 	file, err := ioutil.TempFile("", "db-test-")
> ```

let's use a `file::memory` instead of a file in the filesystem. 
https://github.com/scionproto/scion/blob/master/go/pkg/trust/sqlite/db_test.go#L42
___
*[go/pkg/cs/drkey/export_test.go, line 26 at r2](https://reviewable.io/reviews/juagargi/scion/19#-MJgD9v98_y_bWHL7K_d:-MJgD9v98_y_bWHL7K_e:b17ghzr) ([raw file](https://github.com/juagargi/scion/blob/18468be11f0cf573cbee0cac25751e49a04fefe1/go/pkg/cs/drkey/export_test.go#L26)):*
> ```Go
> 	c.mutex.Lock()
> 	c.timeNowFcn = f
> 	c.mutex.Unlock()
> ```

replace with `defer c.mutex.Unlock()` right after the `c.mutex.Lock()` (it's effectively the same, but it's more readable)


<!-- Sent from Reviewable.io -->

2020-10-19 10:05 UTC, JordiSubira reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/19)* status: 75 of 94 files reviewed, 3 unresolved discussions (waiting on @juagargi)

___
*[go/pkg/cs/drkey/prefetcher.go, line 31 at r1](https://reviewable.io/reviews/juagargi/scion/19#-MIy5fJXB-xmigFrwAAq:-MK-JHCSAevO3p9D0wAj:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/12d655f11c0e3a7eefdaab6b07d03c5243a91430/go/pkg/cs/drkey/prefetcher.go#L31)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

For now add a note in the "to improve" list, that mentions the fetcher should be improved so that it retries even if the underlaying call fails. Also mention we can improve the trigger / timer in it.
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/service_store_test.go, line 107 at r2](https://reviewable.io/reviews/juagargi/scion/19#-MJgJk2Z63Lz0U2GddyN:-MK-Ja547p5Ns8ALS3Cw:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/18468be11f0cf573cbee0cac25751e49a04fefe1/go/pkg/cs/drkey/service_store_test.go#L107)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

let's use a `file::memory` instead of a file in the filesystem. 
https://github.com/scionproto/scion/blob/master/go/pkg/trust/sqlite/db_test.go#L42
</blockquote></details>

Done.
___
*[go/pkg/cs/drkey/export_test.go, line 26 at r2](https://reviewable.io/reviews/juagargi/scion/19#-MJgD9v98_y_bWHL7K_d:-MK-JDeX4iN2r_Xh336S:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/18468be11f0cf573cbee0cac25751e49a04fefe1/go/pkg/cs/drkey/export_test.go#L26)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

replace with `defer c.mutex.Unlock()` right after the `c.mutex.Lock()` (it's effectively the same, but it's more readable)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-19 12:55 UTC, juagargi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 17 of 19 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/19#-:-MK-vWPjB-0ZbVuDG1BG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-19 13:01 UTC, merged