Initial PR
juagargi/scion pull request #2
Opened 2020-03-17 17:21 UTC by joelfischerr

2020-03-24 18:00 UTC, juagargi requested changes
Great start! Some comments:
- remember to amend your commits so that all have the same author. On that note, configure your machines to use the same name and email.
- in the feature branch I see a lot of merge commits. I'd rather rebase feature branches than merge changes into them, as the feature is isolated until published. It's okay to have it like this for now though, as it will be squashed later when merging to the target-develop.

> Reviewed 7 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2#-:-M377RRI2-1SuPDbuJR-:ba8kusq)* status: 7 of 16 files reviewed, 20 unresolved discussions (waiting on @joelfischerr)

___
*[go/border/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37FM1w0rIEMIHHdQeG:-M37FM1w0rIEMIHHdQeH:bg4qcll) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/BUILD.bazel#L17)):*
> ```Starlark
>         "classRule.go",
>         "policer.go",
>         "scheduler.go",
> ```

there are new files not yet included in Bazel. Run `./scion.sh lint` to see the differences (among other things).
___
*[go/border/queue.go, line 1 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37JZAu4AmfaiG0xcTk:-M37JZAu4AmfaiG0xcTl:b-asarns) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L1)):*
> ```Go
> package main
> ```

missing copyright, etc
___
*[go/border/queue.go, line 1 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37Ja6xAJroUXqk068-:-M37Ja6xAJroUXqk0680:b9vas1p) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L1)):*
> ```Go
> package main
> ```

should not be part of main
___
*[go/border/queue.go, line 15 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37JODjC0ajSJ1scDQt:-M37JODjC0ajSJ1scDQu:b-dgfy8e) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L15)):*
> ```Go
> const (
> 	// PASS Pass the packet
> 	PASS policeAction = 0
> ```

`PASS policeAction = iota`
___
*[go/border/queue.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37JSR66DEKo-a-fqeZ:-M37JSR66DEKo-a-fqe_:bkl7ohc) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L17)):*
> ```Go
> 	PASS policeAction = 0
> 	// NOTIFY Notify the sending host of the packet
> 	NOTIFY policeAction = 1
> ```

no need to specify 1, 2, etc. or the type, once you've specified `iota`
___
*[go/border/queue.go, line 27 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37Jmwl1EGMCZSVsugX:-M37Jmwl1EGMCZSVsugY:b-itxl20) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L27)):*
> ```Go
> 
> const (
> 	// None none
> ```

remove these comments
___
*[go/border/queue.go, line 28 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37Jg6380OFIh6uxtLK:-M37Jg6380OFIh6uxtLL:bb7i9p4) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L28)):*
> ```Go
> const (
> 	// None none
> 	None = 0
> ```

iota
___
*[go/border/queue.go, line 47 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37K6Ao176yuDjtJveK:-M37K6Ao176yuDjtJveL:b-vjw4gf) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L47)):*
> ```Go
> 
> type packetQueue struct {
> 	Name         string          `yaml:"name"`
> ```

we separate internal structures from configuration. So there should be a configuration front end that configures the queue system.
___
*[go/border/queue_test.go, line 116 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37DH_52GOKzxhCqCP8:-M37DH_52GOKzxhCqCP9:b-rkd5d4) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue_test.go#L116)):*
> ```Go
> 			t.Errorf("Returned wrong packet!")
> 		} else {
> 			fmt.Println("We got the packet back 🥳👯‍♂️👯‍♀️")
> ```

use `t.Log`
___
*[go/border/test-config.yaml, line 0 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GoIt7bLKLmvWCeZG:-M37GoIt7bLKLmvWCeZH:b-ho378m) ([raw file](https://github.com/juagargi/scion/blob/3ea1e855fc2d39bf58410f06e253fc0435e90715/go/border/test-config.yaml#L0)):*
wow such empty
___
*[go/border/rpkt/BUILD.bazel, line 58 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37F3OT9ESYaD-o1Fwl:-M37F3OT9ESYaD-o1Fwm:bo8rubi) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/BUILD.bazel#L58)):*
> ```Starlark
>         "rpkt_hook_test.go",
>         "rpkt_test.go",
>         "export_test.go"
> ```

there are new files not yet included in Bazel.
___
*[go/border/rpkt/export.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37FXw7DN66RyFAnhMR:-M37FXw7DN66RyFAnhMS:b-jv9bz4) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export.go#L17)):*
> ```Go
> 
> //TODO: Make this be not dumb, I just want this export for tests. But for some reason it doesn't work.
> func JFPrepareRtrPacketSample(t *testing.T) *RtrPkt {
> ```

This function is repeated in the UT.
___
*[go/border/rpkt/export.go, line 67 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37G26J4EdTWvor3F4Y:-M37G26J4EdTWvor3F4Z:bhplf4m) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export.go#L67)):*
> ```Go
> }
> 
> //TODO: Make this be not dumb, I just want this export for tests. But for some reason it doesn't work.
> ```

what is it that doesn't work? the test is also in the `rpkt` package, it's got access to the same things as this file.
___
*[go/border/rpkt/export_test.go, line 16 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GauX8eJoYAOtyxDh:-M37GauX8eJoYAOtyxDi:b-zbofoq) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L16)):*
> ```Go
> )
> 
> func JFPrepareRtrPacketSample(t *testing.T) *RtrPkt {
> ```

check function name
___
*[go/border/rpkt/export_test.go, line 16 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GcxT-YcVMU41qbi3:-M37GcxT-YcVMU41qbi4:b-p1r1zc) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L16)):*
> ```Go
> )
> 
> func JFPrepareRtrPacketSample(t *testing.T) *RtrPkt {
> ```

where is this used?
___
*[go/border/rpkt/export_test.go, line 18 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GjwU1LEkj3zR5jfy:-M37GjwU1LEkj3zR5jfz:b-lbo1s1) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L18)):*
> ```Go
> func JFPrepareRtrPacketSample(t *testing.T) *RtrPkt {
> 	r := NewRtrPkt()
> 	// r.Raw = xtest.MustReadFromFile(t, rawUdpPkt)
> ```

cleanup
___
*[go/border/rpkt/export_test.go, line 36 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GVd8C9JMPsHwAy-R:-M37GVd8C9JMPsHwAy-S:b-dsy7if) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L36)):*
> ```Go
> 	r.Raw = nil // We don't need contents for this anyways
> 	r.TimeIn = time.Now()
> 	r.DirFrom = -1 // I don't know what this is
> ```

look at go/border/rcmn/dir.go
___
*[go/border/rpkt/export_test.go, line 64 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GfaT9lsdfjVNgC6G:-M37GfaT9lsdfjVNgC6H:bw8wd1o) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L64)):*
> ```Go
> 	r.refCnt = -1
> 	return r
> }
> ```

there is no actual test happening in this UT
___
*[go/border/rpkt/rpkt.go, line 168 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37E_E56pUHSsPFWYM3:-M37E_E56pUHSsPFWYM4:bfxs6gd) ([raw file](https://github.com [...]

2020-03-27 14:17 UTC, joelfischerr reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 0 of 12 files reviewed, 20 unresolved discussions (waiting on @juagargi)

___
*[go/border/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37FM1w0rIEMIHHdQeG:-M3RGoX26SCeNwvvN-oK:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/BUILD.bazel#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

there are new files not yet included in Bazel. Run `./scion.sh lint` to see the differences (among other things).
</blockquote></details>

Done.
___
*[go/border/queue.go, line 1 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37JZAu4AmfaiG0xcTk:-M3RGsPU5Gcv0qgpYRD-:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L1)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

missing copyright, etc
</blockquote></details>

Done.
___
*[go/border/queue.go, line 1 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37Ja6xAJroUXqk068-:-M3RHFtf9pABrfhN3kZK:befbedb) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L1)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

should not be part of main
</blockquote></details>

Will change with https://github.com/joelfischerr/scion/pull/6
___
*[go/border/queue.go, line 15 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37JODjC0ajSJ1scDQt:-M3RHSUvDNxgWVv2GQKd:b-dmoc6x) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L15)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

`PASS policeAction = iota`
</blockquote></details>

Also changed in https://github.com/joelfischerr/scion/pull/6
___
*[go/border/queue.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37JSR66DEKo-a-fqeZ:-M3RHTaE6LTY8d4hXC6h:b-dmoc6x) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

no need to specify 1, 2, etc. or the type, once you've specified `iota`
</blockquote></details>

Also changed in https://github.com/joelfischerr/scion/pull/6
___
*[go/border/queue.go, line 27 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37Jmwl1EGMCZSVsugX:-M3RHV1Q1oMmn23SbQuG:b4841iu) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L27)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

remove these comments
</blockquote></details>

Fixed in https://github.com/joelfischerr/scion/pull/6
___
*[go/border/queue.go, line 28 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37Jg6380OFIh6uxtLK:-M3RHWlMDF6HX7w9-Hpa:b4841iu) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L28)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

iota
</blockquote></details>

Fixed in https://github.com/joelfischerr/scion/pull/6
___
*[go/border/queue.go, line 47 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37K6Ao176yuDjtJveK:-M3RHXtEBDILjq_pksFm:b4841iu) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L47)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

we separate internal structures from configuration. So there should be a configuration front end that configures the queue system.
</blockquote></details>

Fixed in https://github.com/joelfischerr/scion/pull/6
___
*[go/border/queue_test.go, line 116 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37DH_52GOKzxhCqCP8:-M3RHs626mKmv7ofEX2f:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue_test.go#L116)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

use `t.Log`
</blockquote></details>

Done.
___
*[go/border/test-config.yaml, line  at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GoIt7bLKLmvWCeZG:-M3RI-VY6bbiThpw59ee:b-sepvrq) ([raw file](https://github.com/juagargi/scion/blob/3ea1e855fc2d39bf58410f06e253fc0435e90715/go/border/test-config.yaml#L)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

wow such empty
</blockquote></details>

Done. Removed the file.
___
*[go/border/rpkt/BUILD.bazel, line 58 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37F3OT9ESYaD-o1Fwl:-M3RI1Cv2CIDKowkeSk6:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/BUILD.bazel#L58)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

there are new files not yet included in Bazel.
</blockquote></details>

Done.
___
*[go/border/rpkt/export.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37FXw7DN66RyFAnhMR:-M3RI2azBihMT9BMxnxe:b80foxs) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export.go#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

This function is repeated in the UT.
</blockquote></details>

Done.  Removed export_test.go
___
*[go/border/rpkt/export.go, line 67 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37G26J4EdTWvor3F4Y:-M3RI62IBw8s3UXDb_GJ:b-th34kc) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export.go#L67)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

what is it that doesn't work? the test is also in the `rpkt` package, it's got access to the same things as this file.
</blockquote></details>

Done. I need this in queue_test.go which is the main package. But I was just confused about how to export this function. This will change when #6 is merged (https://github.com/joelfischerr/scion/pull/6).
___
*[go/border/rpkt/export_test.go, line 16 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GauX8eJoYAOtyxDh:-M3RIlyA5YimtRo5SN3U:b-efgdbq) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L16)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

check function name
</blockquote></details>

Done. File is now deleted.
___
*[go/border/rpkt/export_test.go, line 16 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GcxT-YcVMU41qbi3:-M3RImX60rKQ5lKRv4dg:buq3bru) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L16)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

where is this used?
</blockquote></details>

Done. Nowhere. I have deleted the file.
___
*[go/border/rpkt/export_test.go, line 18 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GjwU1LEkj3zR5jfy:-M3RJTYI9KEvDz40UZKz:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go# [...]

2020-03-27 17:08 UTC, juagargi requested changes
On of the things that I'm missing is a README or part of a README describing how the BR now enqueues or dequeues packets.
I also miss very much documentation on what each function does. E.g. 

> Reviewed 5 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2#-:-M3RWcyk1acq_0YIN5Ws:b5lbiwv)* status: 0 of 12 files reviewed, 43 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[go/border/classRule.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RvoStBLMRAy6jYK71:-M3RvoStBLMRAy6jYK72:b-jmepyd) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L17)):*
> ```Go
> 	Name          string `yaml:"name"`
> 	SourceAs      string `yaml:"sourceAs"`
> 	NextHopAs     string `yaml:"nextHopAs"`
> ```

unused
___
*[go/border/classRule.go, line 19 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RwDe79sbl_qky7Pcf:-M3RwDe79sbl_qky7Pcg:buk93q) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L19)):*
> ```Go
> 	NextHopAs     string `yaml:"nextHopAs"`
> 	DestinationAs string `yaml:"DestinationAs"`
> 	L4Type        []int  `yaml:"L4Type"`
> ```

`L4Types`, and it should be a set of `common.L4ProtocolType` (a set is a map of `struct{}`)
___
*[go/border/classRule.go, line 27 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RuBRF2_nuNISOgi_1:-M3RuBRF2_nuNISOgi_2:bqoxy1f) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L27)):*
> ```Go
> 	queueNo := 0
> 
> 	for _, cr := range *crs {
> ```

getting the queue number is not constant in time, and depends on the number of class rules. How can we improve this?
___
*[go/border/classRule.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RfNop-vc-uVBtnivL:-M3RfNop-vc-uVBtnivM:b-luljg9) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L29)):*
> ```Go
> 	for _, cr := range *crs {
> 		if cr.matchRule(rp) {
> 			queueNo = cr.QueueNumber
> ```

why not return from that point? why keep on looping?
___
*[go/border/classRule.go, line 35 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RtqYh7z5e9vKSIz05:-M3RtqYi0SXu8nFd0-cu:binev7u) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L35)):*
> ```Go
> }
> 
> func (cr *classRule) matchRule(rp *rpkt.RtrPkt) bool {
> ```

it seems `matchRule` needs that both the source and destination addresses in `rpkt` match against the configured values in the `classRule`. How can I then match "any packet going to ffaa:1:1" ?
___
*[go/border/policer.go, line 11 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpoT31IIXbbjeJeCe:-M3RpoT31IIXbbjeJeCf:b-2mz8m6) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L11)):*
> ```Go
> 
> type tokenBucket struct {
> 	MaxBandWidth     int // In bps
> ```

much more clear if we use bytes instead of bits. Let the configuration functions transform the input from e.g. Mbps to bytes
___
*[go/border/policer.go, line 13 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpE5c60RL6HJe1uWd:-M3RpE5c60RL6HJe1uWe:b-1azicf) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L13)):*
> ```Go
> 	MaxBandWidth     int // In bps
> 	tokens           int // One token is 1 b
> 	tokenSpent       int
> ```

we only write to `tokenSpent`, never use the value for anything!
___
*[go/border/policer.go, line 14 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpNqY8umTtDF1Hzv2:-M3RpNqY8umTtDF1Hzv3:b-jmepyd) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L14)):*
> ```Go
> 	tokens           int // One token is 1 b
> 	tokenSpent       int
> 	timerGranularity int
> ```

unused
___
*[go/border/policer.go, line 25 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Ro1l26onUn-pM3LIj:-M3Ro1l26onUn-pM3LIk:b-kglbsi) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L25)):*
> ```Go
> 	timeSinceLastUpdate := now.Sub(tb.lastRefill).Milliseconds()
> 
> 	if shouldLog {
> ```

just `log.Trace` and let the configuration take care of showing it or not
___
*[go/border/policer.go, line 44 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Rpcx2DDU3BsxcysWq:-M3Rpcx2DDU3BsxcysWr:bb7b32r) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L44)):*
> ```Go
> 			tb.tokens = tb.MaxBandWidth
> 		} else {
> 			tb.tokens = tb.tokens + newTokens
> ```

`+=`
___
*[go/border/policer.go, line 51 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RfsLK7DCF1ebdryx4:-M3RfsLK7DCF1ebdryx5:b-8x62xf) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L51)):*
> ```Go
> 
> func (pq *packetQueue) police(qp *qPkt, shouldLog bool) policeAction {
> 	pq.tb.mutex.Lock()
> ```

why not use channels instead of the mutex?
___
*[go/border/policer.go, line 92 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RqB136dcoJ15YrRz3:-M3RqB136dcoJ15YrRz4:brq7op4) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L92)):*
> ```Go
> 	select {
> 	case r.notifications <- qp:
> 	default:
> ```

same comment as in router.go: are you sure the message is sent to the channel?
___
*[go/border/queue.go, line 74 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RqgK26U2fq3ibY8VU:-M3RqgK26U2fq3ibY8VV:b976y6d) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L74)):*
> ```Go
> 	defer pq.mutex.Unlock()
> 
> 	pq.queue = append(pq.queue, rp)
> ```

this is going to be extremely slow. Use a ring buffer instead.
___
*[go/border/queue.go, line 105 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Rr1AsAjyrep8XKmlf:-M3Rr1AsAjyrep8XKmlg:b3grntk) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L105)):*
> ```Go
> 
> 	pkt := pq.queue[0]
> 	pq.queue = pq.queue[1:]
> ```

same as before in `enqueue` regarding performance
___
*[go/border/queue.go, line 127 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RrIQhCZqazEk0n7EX:-M3RrIQhCZqazEk0n7EY:b-51d1th) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L127)):*
> ```Go
> 	level := pq.getFillLevel()
> 
> 	log.Info("Current level is", "level", level)
> ```

all of these should be `Trace` instead
___
*[go/border/queue.go, line 146 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RgvZb5WefWgOV2Ni2:-M3RgvZb5WefWgOV2Ni3:blkle6o) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L146)):*
> ```Go
> 
> func returnAction(polAction policeAction, profAction policeAction) policeAction {
> ```

this can be expressed more efficiently with integers, e.g. 
```go
pol,prof = 3-pol,3-prof
if pol*prof==0 { return DROPNOTIFY }
pol--
prof--
if pol*prof==0 { return DROP }
// ... and so on
```
or if you mapped the constants to prime numbers, you can find out if e..g `pol*prof % 2 == 0` in the order you want.
___
*[go/border/router.go, line 45 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RTHbd2OL5dkGjkJE3:-M3RTHbd2OL5dkGjkJE4:b-mcux3f) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/router.go#L45)):*
> ```Go
> const maxNotificationCount = 512
> 
> const configFileLocation = "/home/fischjoe/go/src/github.com/joelfischerr/scion/go/border/sample-config.yaml"
> ```

this path should be configure in `br.toml`
___
*[go/border/router [...]

2020-03-27 17:46 UTC, juagargi requested changes
> Reviewed 7 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 6 of 12 files reviewed, 42 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[go/border/rpkt/export_test.go, line 16 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GauX8eJoYAOtyxDh:-M3S4_ph17nJJzjRuhQ_:b-vc7edw) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L16)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done. File is now deleted.
</blockquote></details>

all comments in this file apply to the same code in exports.go
___
*[go/border/rpkt/export_test.go, line 16 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GcxT-YcVMU41qbi3:-M3S4un96LSoub42m6ua:b-g43prk) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L16)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done. Nowhere. I have deleted the file.
</blockquote></details>

nono, it's used in queue_test.go
___
*[go/border/rpkt/export_test.go, line 18 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GjwU1LEkj3zR5jfy:-M3S5BvmA0o12r9tYwAb:bp0s2ox) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L18)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please look at the same function in export.go
___
*[go/border/rpkt/export_test.go, line 36 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37GVd8C9JMPsHwAy-R:-M3S5Iaw7DU7aGvXHmvu:b-5o2a9j) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/export_test.go#L36)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please look at the same function in export.go


<!-- Sent from Reviewable.io -->

2020-03-28 11:38 UTC, joelfischerr reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 6 of 12 files reviewed, 43 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[go/border/classRule.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RvoStBLMRAy6jYK71:-M3S5unkEaW-B1DIunBe:bktrucg) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

unused
</blockquote></details>

I thought I might use it in the future. Should I remove it now?
___
*[go/border/classRule.go, line 19 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RwDe79sbl_qky7Pcf:-M3S5ypZ-0PVqVmlkHIQ:b-bpfb9x) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L19)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

`L4Types`, and it should be a set of `common.L4ProtocolType` (a set is a map of `struct{}`)
</blockquote></details>

Done. Will be included in the next changes to classRule.go
___
*[go/border/classRule.go, line 27 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RuBRF2_nuNISOgi_1:-M3S6JZB-IpeFfJNpdI1:bilpslc) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L27)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

getting the queue number is not constant in time, and depends on the number of class rules. How can we improve this?
</blockquote></details>

Done. Will use a hashmap in the future.
___
*[go/border/classRule.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RfNop-vc-uVBtnivL:-M3S74GN0za84_5FkCLt:b-7g84sg) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L29)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

why not return from that point? why keep on looping?
</blockquote></details>

There might be multiple matches. In the next version, a priority can be configured. The match with the highest priority will be used.
___
*[go/border/classRule.go, line 35 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RtqYh7z5e9vKSIz05:-M3S7FdV05QuxL2QCU34:bfmfo1v) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L35)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

it seems `matchRule` needs that both the source and destination addresses in `rpkt` match against the configured values in the `classRule`. How can I then match "any packet going to ffaa:1:1" ?
</blockquote></details>

At the moment this is not possible. But have already changed it.
___
*[go/border/policer.go, line 11 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpoT31IIXbbjeJeCe:-M3Vvh6dAR5QO39Ys2qA:b-77u6kc) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L11)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

much more clear if we use bytes instead of bits. Let the configuration functions transform the input from e.g. Mbps to bytes
</blockquote></details>

Working. Added it to my todolist.
___
*[go/border/policer.go, line 13 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpE5c60RL6HJe1uWd:-M3SIXxc4y5A6whNgmUT:bcysquh) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L13)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

we only write to `tokenSpent`, never use the value for anything!
</blockquote></details>

It is a leftover from debugging. Marc is now using it though.
___
*[go/border/policer.go, line 14 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpNqY8umTtDF1Hzv2:-M3SIfVV4CsDzwamUqaj:b-74bepi) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L14)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done. Removed it.
___
*[go/border/policer.go, line 25 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Ro1l26onUn-pM3LIj:-M3SJaqw5uImHmEmXE_w:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L25)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

just `log.Trace` and let the configuration take care of showing it or not
</blockquote></details>

Done.
___
*[go/border/policer.go, line 44 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Rpcx2DDU3BsxcysWq:-M3S8AyN4bLo0_DIcp9C:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L44)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

`+=`
</blockquote></details>

Done.
___
*[go/border/policer.go, line 51 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RfsLK7DCF1ebdryx4:-M3SLEiF7TDkOKEzWoe6:b-ror8iq) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L51)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

why not use channels instead of the mutex?
</blockquote></details>

Would a channel be better?
___
*[go/border/policer.go, line 92 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RqB136dcoJ15YrRz3:-M3S8Vy7EhyDxvQUZBGb:b-jv168a) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L92)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

same comment as in router.go: are you sure the message is sent to the channel?
</blockquote></details>

No, I have removed for the next version.
___
*[go/border/queue.go, line 74 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RqgK26U2fq3ibY8VU:-M3S8bPcCL4uI5zTKMNu:b3p9h02) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/queue.go#L74)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

this is going to be extremely slow. Use a ring buffer instead.
</blockquote></details>

I think ring buffer is especially fast if multiple enqeueue operations can be put together. But when enqueueing single packets this isn't actually all that bad.
I am currently using channels which are performing reasonably well in my benchmarks.

BenchmarkEnqDequeSingle/Slice_Queue_10_Packets_1_times-4         	        9555192	              126 ns/op	       8 B/op	       1 allocs/op
BenchmarkEnqDequeSingle/Ringbuf_Queue_1_Packets_1_times-4        	 5869380	       201 ns/op	       0 B/op	       0 allocs/op
BenchmarkEnqDequeSingle/Custom_Queue_1_Packets_1_times-4         	14280235	        84.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkEnqDequeSingle/Channel_Queue_1_Packets_1_times-4        	16075989	        74.4 ns/op	       0 B/op	       0 allocs/op

Custom_Queue is my own implementation of a ring buffer
___
*[go/border/queue.go, line 105 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Rr1AsAjyrep8XKmlf:-M3SLInB3uqBRTFVxnkB:b-kxvtq8) ([raw file](https://github.com/juagargi/scion/blob/6 [...]

2020-03-30 17:04 UTC, juagargi requested changes
build fails at the moment, several compile problems in `go/border/qos/qosqueues/classRule.go`

> Reviewed 6 of 15 files at r2, 2 of 35 files at r3, 4 of 50 files at r5.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2#-:-M3gLksw4_Wt8O5PzyfX:blbsebi)* status: 3 of 45 files reviewed, 19 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[go.sum, line 107 at r5](https://reviewable.io/reviews/juagargi/scion/2#-M3gIcL46pzLjpdR2N3w:-M3gIcL46pzLjpdR2N3x:bxy0opd) ([raw file](https://github.com/juagargi/scion/blob/27a700d2df5087f100ed30a641ceb7134c7dc16c/go.sum#L107)):*
> ```
> github.com/prometheus/client_golang v1.1.0 h1:BQ53HtBmfOitExawJ6LokA4x8ov/z0SYYb0+HxJfRI8=
> github.com/prometheus/client_golang v1.1.0/go.mod h1:I1FGZT9+L76gKKOs5djB6ezCbFQP1xR9D75/vuwEF3g=
> github.com/prometheus/client_golang v1.5.1 h1:bdHYieyGlH+6OLEk2YQha8THib30KP0/yD0YH9m6xcA=
> ```

should not be modified
___
*[go/border/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37FM1w0rIEMIHHdQeG:-M3gJZck5wXFXMSK7fCi:bg9jxf0) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/BUILD.bazel#L17)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

run `make gazelle` again
___
*[go/border/border, line 0 at r5](https://reviewable.io/reviews/juagargi/scion/2#-M3gJdtH6WbpiSkSdlv2:-M3gJdtH6WbpiSkSdlv3:bp9q0xk) ([raw file](https://github.com/juagargi/scion/blob/27a700d2df5087f100ed30a641ceb7134c7dc16c/go/border/border#L0)):*
should not be here
___
*[go/border/router.go, line 196 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3ReJmi6lly1UovfgeJ:-M3gMAYc9izFhKtJAXRl:bjx2ltg) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/router.go#L196)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean, cleanup all files, all commented out code that doesn't have a specific meaning
___
*[go/border/rpkt/BUILD.bazel, line 58 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37F3OT9ESYaD-o1Fwl:-M3gO7752NMEK1AfO6Ya:b70de4i) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/BUILD.bazel#L58)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

run `make gazelle` again.
___
*[go/border/classRule.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RvoStBLMRAy6jYK71:-M3gN6T7302URDtmIkjC:b-jbraad) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L17)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

I thought I might use it in the future. Should I remove it now?
</blockquote></details>

yes. Otherwise the review is incorrect or incomplete.
___
*[go/border/classRule.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RfNop-vc-uVBtnivL:-M3gNLYS0apFE9WpWBPy:b-jw0dir) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L29)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

There might be multiple matches. In the next version, a priority can be configured. The match with the highest priority will be used.
</blockquote></details>

if there is no priority now, return when found. You can open a small PR later to modify this.
___
*[go/border/classRule.go, line 35 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RtqYh7z5e9vKSIz05:-M3gNYPFC1oDztdMeeKT:bgwd7u3) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L35)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

At the moment this is not possible. But have already changed it.
</blockquote></details>

alright. We have to add some UT or integration test with the use cases that we need to be represented.
___
*[go/border/policer.go, line 13 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpE5c60RL6HJe1uWd:-M3gNpkuCLithnPZ0fE-:b-9r3l8d) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L13)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

It is a leftover from debugging. Marc is now using it though.
</blockquote></details>

in this review, it's not used. You can remove it and let Marc add it; it will make sense in that context.
___
*[go/border/policer.go, line 51 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RfsLK7DCF1ebdryx4:-M3gNfsz7qldMrWLW8jS:b-rnlm4b) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L51)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Would a channel be better?
</blockquote></details>

it should be faster.


<!-- Sent from Reviewable.io -->

2020-04-09 14:44 UTC, juagargi requested changes
> Reviewed 2 of 35 files at r3, 5 of 50 files at r5, 16 of 27 files at r7, 9 of 10 files at r8, 1 of 4 files at r9, 25 of 39 files at r10, 3 of 4 files at r11, 2 of 2 files at r12, 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 23 of 35 files reviewed, 14 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[go/border/rpkt/export.go, line 81 at r7](https://reviewable.io/reviews/juagargi/scion/2#-M4UNgCD-Fg6SwNrbAwv:-M4UNgCEAjXQUEqOAadR:b-1zjfds) ([raw file](https://github.com/juagargi/scion/blob/a844bd00cfd8d769c32b3d56cab37d69bc99f64d/go/border/rpkt/export.go#L81)):*
> ```Go
> }
> 
> func PrepareRtrPacketWithStrings(sourceIA string, destinationIA string, L4Type int) *RtrPkt {
> ```

Could we use something like `RtrPktFromScnPkt` from create.go instead of exporting this for the UTs?
___
*[go/border/qos/queues/classRule.go, line 44 at r12](https://reviewable.io/reviews/juagargi/scion/2#-M4K0szBCyCKitnXJ053:-M4K0szBCyCKitnXJ054:b-17bkjc) ([raw file](https://github.com/juagargi/scion/blob/4891364c0fe8d4f38b98637a60c13b42f0ece275/go/border/qos/queues/classRule.go#L44)):*
> ```Go
> 
> type InternalClassRule struct {
> 	// This is currently means the ID of the sending border router
> ```

what does this mean?


<!-- Sent from Reviewable.io -->

2020-04-09 14:47 UTC, juagargi reviewed
> Reviewed 12 of 13 files at r14.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: all files reviewed, 9 unresolved discussions (waiting on @joelfischerr)



<!-- Sent from Reviewable.io -->

2020-04-26 15:30 UTC, juagargi requested changes
> Reviewed 2 of 273 files at r15, 2 of 40 files at r16, 153 of 487 files at r17.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 160 of 297 files reviewed, 12 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[init_demo.sh, line 1 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r5ThX8WUdwQKYHVO0:-M5r5ThX8WUdwQKYHVO1:b-bv6gxh) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/init_demo.sh#L1)):*
> ```Shell
> cp go/border/qos/testdata/DemoConfig.yaml gen/ISD1/ASff00_0_110/br1-ff00_0_110-1/qosConfig.yaml
> ```

can we move this file to the secondary PR where things are set up for the demo?
___
*[tc-script.sh, line 1 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r5N4p61K5BhdESTNk:-M5r5N4p61K5BhdESTNl:b1x9e2x) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/tc-script.sh#L1)):*
> ```Shell
> tc qdisc del dev lo root
> ```

do we need this file?
___
*[python/topology/go.py, line 101 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r3zU01VAMQWuLB0Dc:-M5r3zU1734PKYv8-n8p:b-lq1e3d) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/python/topology/go.py#L101)):*
> ```Python
> 
>     def _copy_qos_conf(self, path, base, name):
>         dest_file = '/share/conf/qosConfig.yaml' if self.args.docker else os.path.join(base, name, 'qosConfig.yaml')
> ```

where is that `qosConfig.yaml` been generated?


<!-- Sent from Reviewable.io -->

2020-04-26 17:02 UTC, joelfischerr reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 158 of 294 files reviewed, 10 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[go.sum, line 107 at r5](https://reviewable.io/reviews/juagargi/scion/2#-M3gIcL46pzLjpdR2N3w:-M3gr-cFDERQF2PAoHqJ:b40xmrh) ([raw file](https://github.com/juagargi/scion/blob/27a700d2df5087f100ed30a641ceb7134c7dc16c/go.sum#L107)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

should not be modified
</blockquote></details>

Done. Have reverted the change
___
*[init_demo.sh, line 1 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r5ThX8WUdwQKYHVO0:-M5rNmGU8TAvAiSxwZnG:b-ysye1b) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/init_demo.sh#L1)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

can we move this file to the secondary PR where things are set up for the demo?
</blockquote></details>

Done. Secondary with the stuff for the demo will be jf-master.
___
*[tc-script.sh, line 1 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r5N4p61K5BhdESTNk:-M5rEWA_Ahxu2v-ZmTVS:b-xuydcc) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/tc-script.sh#L1)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

do we need this file?
</blockquote></details>

No. I have removed it
___
*[go/border/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37FM1w0rIEMIHHdQeG:-M3gU1FMBE5thPguyyzS:begbz48) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/BUILD.bazel#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

run `make gazelle` again
</blockquote></details>

oh, I thought I had to do that manually. Should be fixed now
___
*[go/border/border, line  at r5](https://reviewable.io/reviews/juagargi/scion/2#-M3gJdtH6WbpiSkSdlv2:-M3gUSKA4jgPeLXQGtB6:b1y5uio) ([raw file](https://github.com/juagargi/scion/blob/27a700d2df5087f100ed30a641ceb7134c7dc16c/go/border/border#L)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

should not be here
</blockquote></details>

Done. Deleted
___
*[go/border/router.go, line 45 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RTHbd2OL5dkGjkJE3:-M3lrWUDABIUo7BexWkn:b9zl7kq) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/router.go#L45)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Working. Added to my todolist
</blockquote></details>

Done. Needs some cleanup.
___
*[go/border/router.go, line 79 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RUmGq-Km-scqMfGEZ:-M3opY7jA_Z_rrv2vIxC:be22nn6) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/router.go#L79)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Working. Added to my todolist.
</blockquote></details>

Done. There are some leftover datastructures and comments because I needed to rework quite a lot of things to make it work. They should be gone by the end of the week though.
___
*[go/border/scheduler.go, line 4 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RWJ2JCqYJCYa-Po6o:-M3griNN-GRqOzkdFhQQ:bmtokbg) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/scheduler.go#L4)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Working. Put it onto the todolist.
</blockquote></details>

Done. This should be done by now.
___
*[go/border/scheduler.go, line 20 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Rs6xG7zszJ5K-dqTy:-M3grqaw7yzy2TTLYy2L:b-4cgfbq) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/scheduler.go#L20)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Working. Put it onto the todolist.
</blockquote></details>

Done. I have also tried to do this. Was this what you had in mind?
___
*[go/border/rpkt/BUILD.bazel, line 58 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M37F3OT9ESYaD-o1Fwl:-M3gq_jw2e4h3iULNWtr:b-gxkyss) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/rpkt/BUILD.bazel#L58)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

run `make gazelle` again.
</blockquote></details>

I think I have now finally managed to do it.
___
*[go/border/rpkt/export.go, line 81 at r7](https://reviewable.io/reviews/juagargi/scion/2#-M4UNgCD-Fg6SwNrbAwv:-M5rLyYE5JUsa1ev7lrE:bzclbdy) ([raw file](https://github.com/juagargi/scion/blob/a844bd00cfd8d769c32b3d56cab37d69bc99f64d/go/border/rpkt/export.go#L81)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Could we use something like `RtrPktFromScnPkt` from create.go instead of exporting this for the UTs?
</blockquote></details>

Done. I have changed it to use RtrPktFromScnPkt. export.go has been deleted
___
*[python/topology/go.py, line 101 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r3zU01VAMQWuLB0Dc:-M5rFLq28fD0Mc48U_3P:b71pe8c) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/python/topology/go.py#L101)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

where is that `qosConfig.yaml` been generated?
</blockquote></details>

It is copied when generating a topology
___
*[go/border/classRule.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RvoStBLMRAy6jYK71:-M3gWHkgB61DQDnqp1du:b-mnjex1) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L17)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

yes. Otherwise the review is incorrect or incomplete.
</blockquote></details>

Done. I have removed it.
___
*[go/border/classRule.go, line 29 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RfNop-vc-uVBtnivL:-M3gpjbs7ag_sFVWYvRR:b-yomjoh) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L29)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

if there is no priority now, return when found. You can open a small PR later to modify this.
</blockquote></details>

There is. It is already implemented and to make sure it works I have added a test in https://github.com/joelfischerr/scion/pull/24/commits/d6cf52d29f133f54378bd971e5ea954f5c20c0c0
___
*[go/border/classRule.go, line 35 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RtqYh7z5e9vKSIz05:-M3kyY713yrtVYb62HU_:b-y7m60o) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/classRule.go#L35)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

alright. We have to add some UT or integration test with the use cases that we need to be represented.
</blockquote></details>

Working.
___
*[go/border/policer.go, line 11 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3RpoT31IIXbbjeJeCe:-M3gqYuk9IvN5RO7qdAu:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/policer.go#L11)):*
<deta [...]

2020-04-26 19:15 UTC, juagargi requested changes
> Reviewed 2 of 29 files at r18.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 158 of 294 files reviewed, 2 unresolved discussions (waiting on @joelfischerr and @juagargi)

___
*[init_demo.sh, line 1 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r5ThX8WUdwQKYHVO0:-M5ruG2q4HmRhyGPG5DT:b-3hrxy3) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/init_demo.sh#L1)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done. Secondary with the stuff for the demo will be jf-master.
</blockquote></details>

hmm I still see the file here. Are you sure you pushed?
___
*[go/border/scheduler.go, line 20 at r1](https://reviewable.io/reviews/juagargi/scion/2#-M3Rs6xG7zszJ5K-dqTy:-M5rrzDt9nAhgqRQCEug:b-8fx2u7) ([raw file](https://github.com/juagargi/scion/blob/6f8f34f7fae02821c460ed7a2d7407fb0a04b539/go/border/scheduler.go#L20)):*
<details><summary><i>Previously, joelfischerr (Joel) wrote…</i></summary><blockquote>

Done. I have also tried to do this. Was this what you had in mind?
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2020-04-26 19:26 UTC, juagargi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 273 files at r15, 18 of 487 files at r17, 1 of 29 files at r18, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2#-:-M5rx1WFAekdgCQJmbCX:bg7igkv)* status: 174 of 287 files reviewed, 1 unresolved discussion (waiting on @joelfischerr and @juagargi)



<!-- Sent from Reviewable.io -->

2020-04-26 19:27 UTC, juagargi approved these changes
> Reviewed 1 of 487 files at r17.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 174 of 287 files reviewed, 1 unresolved discussion (waiting on @joelfischerr and @juagargi)



<!-- Sent from Reviewable.io -->

2020-04-26 19:28 UTC, joelfischerr reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 174 of 287 files reviewed, all discussions resolved (waiting on @juagargi)

___
*[init_demo.sh, line 1 at r17](https://reviewable.io/reviews/juagargi/scion/2#-M5r5ThX8WUdwQKYHVO0:-M5rv8IR22m7o98Cd1xA:b-etealu) ([raw file](https://github.com/juagargi/scion/blob/982ab9de1b270838c59d687e769d9e1c17a8765b/init_demo.sh#L1)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

hmm I still see the file here. Are you sure you pushed?
</blockquote></details>

Done. Now finally.


<!-- Sent from Reviewable.io -->

2020-04-26 19:28 UTC, juagargi approved these changes
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: 174 of 287 files reviewed, all discussions resolved (waiting on @juagargi)



<!-- Sent from Reviewable.io -->

2020-04-26 19:29 UTC, juagargi approved these changes
> Reviewed 6 of 40 files at r16, 86 of 487 files at r17, 21 of 29 files at r18.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/2)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-04-26 19:29 UTC, merged