colibri border router
juagargi/scion pull request #24
Opened 2021-01-19 14:52 UTC by mawyss

Implementation of the colibri library, the colibri packet format, and the border router forwarding logic.

Overview:
- **go/lib/colibri/**: contains methods for the creation and verification of the colibri packet timestamp and validation fields.
- **go/lib/slayers/path/colibri/**: implements the colibri path type layer. There is a full representation of a colibri path (colibri.go) and a minimal representation (colibri_minimal.go), which is optimized for the border router. 
- **go/pkg/router/colibri_processing.go**: the actual router forwarding logic.

2021-01-20 13:34 UTC, juagargi requested changes
Very nice !
Thank you @mawyss for this contribution. I left only some comments about small issues I found.

> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/24#-:-MRUzxlv1IJScRfkFlca:b-h8lq3e)* status: all files reviewed, 9 unresolved discussions (waiting on @mawyss)

___
*[go/lib/colibri/colibri.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRTyrwT6goJNtagHQHM:-MRTyrwT6goJNtagHQHN:b-xhrisz) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/colibri/colibri.go#L17)):*
> ```Go
> // Package colibri contains methods for the creation and verification of the colibri packet
> // timestamp and validation fields.
> package colibri
> ```

Since the file and package contain only functions related to COLIBRI MAC, what about changing the name of the file and package?
___
*[go/lib/colibri/colibri_test.go, line 242 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUyfWM5q6FKoB9Q9oW:-MRUyfWM5q6FKoB9Q9oX:b-dwjccq) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/colibri/colibri_test.go#L242)):*
> ```Go
> 
> func randUint64() uint64 {
> 	return uint64(rand.Uint32())<<32 + uint64(rand.Uint32())
> ```

We should try not to use random input in our unit tests. There are several reasons for this, among others:
- Difficult to estimate coverage.
- Difficult (sometimes) to reproduce.
- Sometimes frees us from looking for edge cases, under the false pretense they will be eventually caught.
- Fuzzing does exactly this ("random" parameters), but not in the unit tests.
___
*[go/lib/slayers/path/colibri/colibri.go, line 24 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUohld6hVF2DhXUPY4:-MRUohld6hVF2DhXUPY5:b-a7h9b2) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri.go#L24)):*
> ```Go
> )
> 
> type ColibriPath struct {
> ```

Where is the `ColibriPath` used at?
Why do we need a different type than `ColibriPathMinimal` ?
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 40 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUv0I3BEotCg89PfOR:-MRUv0I3BEotCg89PfOS:b-c2k2hd) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L40)):*
> ```Go
> }
> 
> type ColibriPathMinimal struct {
> ```

It would be nice to have some doc string here.
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 120 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUuXxD4f_hjoWBw3OR:-MRUuXxE4EFVcOS7OUnH:b-lp3qg7) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L120)):*
> ```Go
> // serialized. Then the Raw buffer is copied to b.
> func (c *ColibriPathMinimal) SerializeTo(b []byte) error {
> 	if len(b) < c.Len() {
> ```

I realize that the signature of the function comes from an interface, and we don't want to change it. Since it doesn't return the length of the bytes serialized, can we check that the buffer is exactly `Len()` bytes long?

Same would apply for `SerializeToInternal`
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 176 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUpgtR48-POp8TEZ-t:-MRUpgtS87geI7dNADNx:bw5v8ye) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L176)):*
> ```Go
> }
> 
> // UpdateCurrHF increases/decreases the CurrHF index depending on the R flag.
> ```

We should update the comment to indicate it doesn't depend on `R` anymore.
___
*[go/lib/slayers/path/colibri/hopfield_test.go, line 66 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUzoL-4JuBRHG9y6Qu:-MRUzoL-4JuBRHG9y6Qv:b-xudc0l) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/hopfield_test.go#L66)):*
> ```Go
> func randBytes(l uint16) []byte {
> 	r := make([]byte, l)
> 	rand.Read(r)
> ```

As mentioned in the colibri_test, let's avoid random inputs.
___
*[go/pkg/router/colibri_processing.go, line 146 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUOilF3hLCxqk-jU1C:-MRUOilF3hLCxqk-jU1D:b-mcanp4) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/colibri_processing.go#L146)):*
> ```Go
> 
> 	if c.ingressID == 0 {
> 		// Received packet from within AS
> ```

According to your comment, we could use this fact to check that if `C=1` the sender's address is that of a COLIBRI service.
(we will assume that the AS checks no spoofing for the service address happens).
This can be done in a later iteration, it's not necessary to implement it in this PR :smiley: 
___
*[go/pkg/router/colibri_processing.go, line 163 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUkr-k6gn4nuiOKL9Y:-MRUkr-k6gn4nuiOKL9Z:btah7ta) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/colibri_processing.go#L163)):*
> ```Go
> 				return r, err
> 			}
> 			return c.forwardToRemoteEgress(egressId)
> ```

We are ignoring errors from `forwardToLocalEgress`. Why not make the decision here of BR transit or AS transit?
___
*[go/pkg/router/control/conf.go, line 119 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRU-Qs47v8k09-3nLVY:-MRU-Qs56YTGNTilUXj4:b35ns87) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/control/conf.go#L119)):*
> ```Go
> 
> // DeriveColibriKey derives the private Colibri key from the given key.
> func DeriveColibriKey(k []byte) []byte {
> ```

Why not use the `scrypto.DeriveColibriKey` function?
I also wonder why the regular SCION `DeriveHFMacKey` is not using `scrypto` as well.


<!-- Sent from Reviewable.io -->

2021-01-21 13:53 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/24)* status: 17 of 23 files reviewed, 9 unresolved discussions (waiting on @juagargi)

___
*[go/lib/colibri/colibri.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRTyrwT6goJNtagHQHM:-MRZPMZe5PX84Xmxz4d8:b990dus) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/colibri/colibri.go#L17)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Since the file and package contain only functions related to COLIBRI MAC, what about changing the name of the file and package?
</blockquote></details>

The package also contains methods for the creation/verification of timestamps (expiration tick and high precision packet timestamp). It is possible that the colibri package will need to be extended later to the requirements of the end hosts, so I did not go for a more specific name. For the epic PR I received feedback to name the package simply "epic" (the package contains also methods regarding timestamps and MACs), so having "colibri" here would be consistent. Or do you anticipate having a colibri library package for the colibri service, so that it conflicts with this one?
___
*[go/lib/colibri/colibri_test.go, line 242 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUyfWM5q6FKoB9Q9oW:-MR_25CfBMUTkIZuSHAF:b95r3iw) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/colibri/colibri_test.go#L242)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

We should try not to use random input in our unit tests. There are several reasons for this, among others:
- Difficult to estimate coverage.
- Difficult (sometimes) to reproduce.
- Sometimes frees us from looking for edge cases, under the false pretense they will be eventually caught.
- Fuzzing does exactly this ("random" parameters), but not in the unit tests.
</blockquote></details>

Done. Replaced random input with static values.
___
*[go/lib/slayers/path/colibri/colibri.go, line 24 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUohld6hVF2DhXUPY4:-MRZSApx-p_t4VN6B79k:bjnjmm3) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri.go#L24)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Where is the `ColibriPath` used at?
Why do we need a different type than `ColibriPathMinimal` ?
</blockquote></details>

The ColibriPath is currently used in the router unit tests (dataplane_test.go). It will be needed to create colibri packets at the hosts later. Note that also the SCION path type has different representations (decoded vs. raw).
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 40 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUv0I3BEotCg89PfOR:-MRZX01r3nZJsoy1P588:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L40)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

It would be nice to have some doc string here.
</blockquote></details>

Done.
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 120 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUuXxD4f_hjoWBw3OR:-MRZXiNM4nfaTtOvWMCD:b-gdk1ll) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L120)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I realize that the signature of the function comes from an interface, and we don't want to change it. Since it doesn't return the length of the bytes serialized, can we check that the buffer is exactly `Len()` bytes long?

Same would apply for `SerializeToInternal`
</blockquote></details>

I am not sure whether this would work: usually there is a buffer (e.g. 1500 bytes), and each layer gets serialized one after the other, so the buffer can actually be larger than c.Len(). Also the SCION path type implementation checks for "<" and not for "=".
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 176 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUpgtR48-POp8TEZ-t:-MRZZSr_-s058vHQm5u0:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L176)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

We should update the comment to indicate it doesn't depend on `R` anymore.
</blockquote></details>

Done.
___
*[go/lib/slayers/path/colibri/hopfield_test.go, line 66 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUzoL-4JuBRHG9y6Qu:-MR_ApX594_feLdFvm54:b-896fix) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/hopfield_test.go#L66)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

As mentioned in the colibri_test, let's avoid random inputs.
</blockquote></details>

Done.
___
*[go/pkg/router/colibri_processing.go, line 146 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUOilF3hLCxqk-jU1C:-MRZZy-TBZSaqL4CH4K1:bra6jjx) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/colibri_processing.go#L146)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

According to your comment, we could use this fact to check that if `C=1` the sender's address is that of a COLIBRI service.
(we will assume that the AS checks no spoofing for the service address happens).
This can be done in a later iteration, it's not necessary to implement it in this PR :smiley: 
</blockquote></details>

Ok, let's do that later. We need to be a bit careful at on-path ASes, because the source host in the address header of the COLIBRI packet denotes a service within the first AS (if it is an IP address).
Could it make sense to only use service identifiers for C=1 instead of actual IPs?
___
*[go/pkg/router/colibri_processing.go, line 163 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUkr-k6gn4nuiOKL9Y:-MRZrdsB4avWw2PgU7gk:b-5k1zt3) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/colibri_processing.go#L163)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

We are ignoring errors from `forwardToLocalEgress`. Why not make the decision here of BR transit or AS transit?
</blockquote></details>

I am not sure what you mean: the decision of BR transit or AS transit is actually made at this point. The router tries to forward the packet itself to the given egress interface (BR transit), and if that fails (because the router is not responsible for that interface) it forwards the packet to the appropriate border router (AS transit).
___
*[go/pkg/router/control/conf.go, line 119 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRU-Qs47v8k09-3nLVY:-MRZuwyL7Zn4PN60hDm9:b-hsx8qx) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/control/conf.go#L119)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Why not use the `scrypto.DeriveColibriKey` function?
I also wonder why the regular SCION `DeriveHFMacKey` is not using `scrypto` as well.
</blockquote></details>

Good question. I was asking this myself too, and decided to implement it in the same way as with standard SCION to omit any undesirable side effects. 
My guess would be that the router should be light-weight, and not need to import also asymmetric crypto functionality a [...]

2021-01-26 16:07 UTC, juagargi requested changes
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/24)* status: 13 of 23 files reviewed, 2 unresolved discussions (waiting on @juagargi and @mawyss)

___
*[go/lib/colibri/colibri.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRTyrwT6goJNtagHQHM:-MRzEYriAuToPIqu8sVU:b-b30juz) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/colibri/colibri.go#L17)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

The package also contains methods for the creation/verification of timestamps (expiration tick and high precision packet timestamp). It is possible that the colibri package will need to be extended later to the requirements of the end hosts, so I did not go for a more specific name. For the epic PR I received feedback to name the package simply "epic" (the package contains also methods regarding timestamps and MACs), so having "colibri" here would be consistent. Or do you anticipate having a colibri library package for the colibri service, so that it conflicts with this one?
</blockquote></details>

Alright, let's keep it like that at least for now (or forever).
___
*[go/lib/slayers/path/colibri/colibri.go, line 24 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUohld6hVF2DhXUPY4:-MRzH9Wn3ucvQ07Z-5YB:b-8fx2u7) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri.go#L24)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

The ColibriPath is currently used in the router unit tests (dataplane_test.go). It will be needed to create colibri packets at the hosts later. Note that also the SCION path type has different representations (decoded vs. raw).
</blockquote></details>

:+1: 
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 120 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUuXxD4f_hjoWBw3OR:-MRzNG_511CDeKeHZnNh:b8viya5) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L120)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

I am not sure whether this would work: usually there is a buffer (e.g. 1500 bytes), and each layer gets serialized one after the other, so the buffer can actually be larger than c.Len(). Also the SCION path type implementation checks for "<" and not for "=".
</blockquote></details>

I marked this comment as resolved, as the discussion is non blocking for the PR, and only informative.

Structs like `InfoField` are serialized only from this code. In this code we call their `SerializeTo` with a slice with the exact size. They could check for the exact size.

What I meant is that these methods `SerializeTo(_ []byte)` come from the `Path` interface. It is called upon a `Path` object in `SCION.SerializeTo` 
https://github.com/mawyss/scion/blob/colibri_dataplane/go/lib/slayers/scion.go#L181
where the `buf` is allocated with the size computed from calling `Len` (so the exact size).

I would (but not now) change the interface of `SerializeTo`, so that it would return the size of the serialized version, so that it can be called upon a big enough buffer (with more bytes than just `Len`) that does not need to be reallocated every time. But we are not going to change the interface now: that is what I meant with "don't want to change it").
After checking the rest of the implementers of the `Path.SerializeTo` prototype, I see that all check for the length to be sufficient --and not exact--, so I actually prefer to leave it as you coded it.
___
*[go/pkg/router/colibri_processing.go, line 163 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUkr-k6gn4nuiOKL9Y:-MRzQHO0Ez8UlY1EAU8I:bk0vklv) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/colibri_processing.go#L163)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

I am not sure what you mean: the decision of BR transit or AS transit is actually made at this point. The router tries to forward the packet itself to the given egress interface (BR transit), and if that fails (because the router is not responsible for that interface) it forwards the packet to the appropriate border router (AS transit).
</blockquote></details>

Let's trace a call to this function `foward()`: let's say the packet has `C=0`, so we arrive at:
```golang
	} else {
		// Data plane forwarding
		if c.destinedToLocalHost(egressId) {
			return c.forwardToLocalHost()
		} else {
			if r, err := c.forwardToLocalEgress(egressId); err == nil {
				return r, err
			}
			return c.forwardToRemoteEgress(egressId)
		}
	}
```
In there, let's say that `destinedToLocalHost` returns `false`. We end up calling `forwardToLocalEgress`. Let's say that `forwardToLocalEgress` returns an error: looking at that function, a problem updating the current hop field or serializing would do. Then, since we have:
```golang
			if r, err := c.forwardToLocalEgress(egressId); err == nil {
				return r, err
			}
			return c.forwardToRemoteEgress(egressId)
```
we will directly call `forwardToRemoteEgress`. But the packet was meant to be forwarded to local egress, and to report an error. Not to be sent to remote egress.
___
*[go/pkg/router/control/conf.go, line 119 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRU-Qs47v8k09-3nLVY:-MRzHvhu5GnwziwsbDfC:b-ok856s) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/control/conf.go#L119)):*
<details><summary><i>Previously, mawyss wrote…</i></summary><blockquote>

Good question. I was asking this myself too, and decided to implement it in the same way as with standard SCION to omit any undesirable side effects. 
My guess would be that the router should be light-weight, and not need to import also asymmetric crypto functionality as would be the case in the scrypto package.
</blockquote></details>

Idk. To be honest, I would change this and also the regular SCION to use the respective functions from `scrypto`.
Please leave a `TODO(mawyss)` so we (or someone else) will check at a later point (or remove the TODO).


<!-- Sent from Reviewable.io -->

2021-01-28 12:31 UTC, mawyss reviewed
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/24)* status: 13 of 23 files reviewed, 2 unresolved discussions (waiting on @juagargi)

___
*[go/lib/colibri/colibri.go, line 17 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRTyrwT6goJNtagHQHM:-MS7Hbi3BAXuq58vjvgY:b2nhll9) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/colibri/colibri.go#L17)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Alright, let's keep it like that at least for now (or forever).
</blockquote></details>

Ok.
___
*[go/lib/slayers/path/colibri/colibri_minimal.go, line 120 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUuXxD4f_hjoWBw3OR:-MS7HlO33R_9k7ewxgBU:b-i0pvgd) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/lib/slayers/path/colibri/colibri_minimal.go#L120)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

I marked this comment as resolved, as the discussion is non blocking for the PR, and only informative.

Structs like `InfoField` are serialized only from this code. In this code we call their `SerializeTo` with a slice with the exact size. They could check for the exact size.

What I meant is that these methods `SerializeTo(_ []byte)` come from the `Path` interface. It is called upon a `Path` object in `SCION.SerializeTo` 
https://github.com/mawyss/scion/blob/colibri_dataplane/go/lib/slayers/scion.go#L181
where the `buf` is allocated with the size computed from calling `Len` (so the exact size).

I would (but not now) change the interface of `SerializeTo`, so that it would return the size of the serialized version, so that it can be called upon a big enough buffer (with more bytes than just `Len`) that does not need to be reallocated every time. But we are not going to change the interface now: that is what I meant with "don't want to change it").
After checking the rest of the implementers of the `Path.SerializeTo` prototype, I see that all check for the length to be sufficient --and not exact--, so I actually prefer to leave it as you coded it.
</blockquote></details>

Ok, then let's keep this then.
___
*[go/pkg/router/colibri_processing.go, line 163 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRUkr-k6gn4nuiOKL9Y:-MS7eZ6mCjJPmiZVtJZ2:bt623bj) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/colibri_processing.go#L163)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Let's trace a call to this function `foward()`: let's say the packet has `C=0`, so we arrive at:
```golang
	} else {
		// Data plane forwarding
		if c.destinedToLocalHost(egressId) {
			return c.forwardToLocalHost()
		} else {
			if r, err := c.forwardToLocalEgress(egressId); err == nil {
				return r, err
			}
			return c.forwardToRemoteEgress(egressId)
		}
	}
```
In there, let's say that `destinedToLocalHost` returns `false`. We end up calling `forwardToLocalEgress`. Let's say that `forwardToLocalEgress` returns an error: looking at that function, a problem updating the current hop field or serializing would do. Then, since we have:
```golang
			if r, err := c.forwardToLocalEgress(egressId); err == nil {
				return r, err
			}
			return c.forwardToRemoteEgress(egressId)
```
we will directly call `forwardToRemoteEgress`. But the packet was meant to be forwarded to local egress, and to report an error. Not to be sent to remote egress.
</blockquote></details>

Done. The errors should now be properly returned.
___
*[go/pkg/router/control/conf.go, line 119 at r1](https://reviewable.io/reviews/juagargi/scion/24#-MRU-Qs47v8k09-3nLVY:-MS7xe4g-tXzhp-UATiP:b-uv7q69) ([raw file](https://github.com/juagargi/scion/blob/879a56a545884549bb4efb7a6f8749038fcdca60/go/pkg/router/control/conf.go#L119)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Idk. To be honest, I would change this and also the regular SCION to use the respective functions from `scrypto`.
Please leave a `TODO(mawyss)` so we (or someone else) will check at a later point (or remove the TODO).
</blockquote></details>

Done. I added a comment regarding this. In the scionproto slack I asked about the reason for this, so we will hopefully know soon.


<!-- Sent from Reviewable.io -->

2021-01-28 13:24 UTC, juagargi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 11 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/juagargi/scion/24#-:-MS89Z1IEJOwcu8adgkt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)



<!-- Sent from Reviewable.io -->

2021-01-28 13:25 UTC, merged